# Generated by Django 4.0.6 on 2022-08-16 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0023_rename_file_1_board_file_remove_board_file_2_and_more'),
        ('App_Files', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='file',
        ),
        migrations.AddField(
            model_name='files',
            name='board',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to='App_Board.board'),
            preserve_default=False,
        ),
    ]
