# Generated by Django 4.0.6 on 2022-08-16 04:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0023_rename_file_1_board_file_remove_board_file_2_and_more'),
        ('App_Files', '0002_remove_files_file_files_board'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='file',
            field=models.FileField(default=1, upload_to='..media/file/자료 취합/통합 파일'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='board',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App_Board.board'),
        ),
    ]
