# Generated by Django 4.0.6 on 2022-08-16 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Files', '0003_files_file_alter_files_board'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='media/file/자료 취합/취합 파일'),
        ),
    ]
