# Generated by Django 4.0.6 on 2022-08-16 07:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0023_rename_file_1_board_file_remove_board_file_2_and_more'),
        ('App_Files', '0004_alter_files_file'),
    ]

    operations = [
        migrations.RenameField(
            model_name='files',
            old_name='category',
            new_name='s_category',
        ),
        migrations.AddField(
            model_name='files',
            name='l_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='App_Board.category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(upload_to='file/자료 취합/취합 파일'),
        ),
    ]
