# Generated by Django 4.0.6 on 2022-08-18 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Files', '0005_rename_category_files_s_category_files_l_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='files',
            name='l_category',
        ),
        migrations.AlterField(
            model_name='files',
            name='file',
            field=models.FileField(null=True, upload_to='file/자료 취합/취합 파일'),
        ),
    ]
