# Generated by Django 4.0.6 on 2022-08-18 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0023_rename_file_1_board_file_remove_board_file_2_and_more'),
        ('App_Files', '0006_remove_files_l_category_alter_files_file'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['-id']},
        ),
        migrations.AlterField(
            model_name='files',
            name='board',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Board.board'),
        ),
    ]
