# Generated by Django 4.0.6 on 2022-08-18 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Files', '0008_files_created_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
