# Generated by Django 4.0.6 on 2022-08-19 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Files', '0010_errorlog'),
    ]

    operations = [
        migrations.RenameField(
            model_name='errorlog',
            old_name='error',
            new_name='title',
        ),
    ]
