# Generated by Django 4.2.3 on 2023-07-27 16:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0025_rename_post_context_board_post_content_and_more'),
        ('App_Files', '0013_alter_errorlog_error_message'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integrated_Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='file/자료 취합/취합 파일')),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.RenameModel(
            old_name='S_Category',
            new_name='File_Category',
        ),
        migrations.DeleteModel(
            name='Files',
        ),
        migrations.AddField(
            model_name='integrated_files',
            name='file_category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='files', to='App_Files.file_category'),
        ),
        migrations.AddField(
            model_name='integrated_files',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='App_Board.board'),
        ),
    ]
