# Generated by Django 4.2.3 on 2023-07-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Files', '0015_remove_integrated_files_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='integrated_files',
            name='integrated_file',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
