# Generated by Django 4.2.3 on 2023-07-31 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Files', '0016_integrated_files_integrated_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrated_files',
            name='integrated_file',
            field=models.FileField(default=None, null=True, upload_to=''),
        ),
    ]
