# Generated by Django 4.0.6 on 2022-07-28 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0002_alter_board_post_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='slug',
        ),
        migrations.AlterField(
            model_name='board',
            name='post_context',
            field=models.TextField(max_length=1000),
        ),
    ]
