# Generated by Django 4.0.6 on 2022-07-28 07:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Board', '0003_remove_board_slug_alter_board_post_context'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='board',
            name='post_writer',
        ),
        migrations.AddField(
            model_name='board',
            name='post_author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
