# Generated by Django 4.0.6 on 2022-08-02 05:26

import App_Board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0005_alter_board_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='post_file',
            field=models.FileField(blank=True),
        ),
    ]
