# Generated by Django 4.0.6 on 2022-08-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0012_editlog_remove_board_edit_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='editlog',
            name='board',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='editlogs', to='App_Board.board'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='editlog',
            name='edit_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
