# Generated by Django 4.0.6 on 2022-08-03 16:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('App_Board', '0013_editlog_board_alter_editlog_edit_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='editlog',
            name='eidtor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
