# Generated by Django 4.0.6 on 2022-08-04 14:39

import App_Board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0016_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='file',
            field=models.FileField(default=1, upload_to=App_Board.models.file_dir_path, verbose_name='파일 경로'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
