# Generated by Django 4.0.6 on 2022-08-04 14:48

import App_Board.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0017_board_file_delete_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=App_Board.models.file_dir_path, verbose_name='파일 경로'),
        ),
    ]
