# Generated by Django 4.0.6 on 2022-08-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0022_rename_file_board_file_1_board_file_2_board_file_3'),
    ]

    operations = [
        migrations.RenameField(
            model_name='board',
            old_name='file_1',
            new_name='file',
        ),
        migrations.RemoveField(
            model_name='board',
            name='file_2',
        ),
        migrations.RemoveField(
            model_name='board',
            name='file_3',
        ),
    ]
