# Generated by Django 4.0.6 on 2022-08-20 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0023_rename_file_1_board_file_remove_board_file_2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='board',
            name='counting',
            field=models.IntegerField(default=0),
        ),
    ]
