# Generated by Django 4.2.3 on 2023-07-28 09:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('App_Board', '0025_rename_post_context_board_post_content_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='files',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
