# Generated by Django 4.0.6 on 2022-08-02 08:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(choices=[('A01', '회사 1'), ('A02', '회사 2'), ('A03', '회사 3'), ('A04', '회사 4'), ('A05', '회사 5'), ('A06', '회사 6'), ('A07', '회사 7')], max_length=30),
        ),
    ]
