# Generated by Django 4.0.6 on 2022-08-02 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0002_alter_user_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=30),
        ),
    ]
