# Generated by Django 4.2.3 on 2023-07-26 07:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0003_alter_user_company'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_tel',
            new_name='phone_number',
        ),
    ]
