# Generated by Django 4.2.3 on 2023-08-07 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0009_emailverification_user_alter_emailverification_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverification',
            name='is_verificate',
            field=models.BooleanField(default=False),
        ),
    ]
