# Generated by Django 4.2.3 on 2023-08-21 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App_Auth', '0010_emailverification_is_verificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verificate',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='user',
            name='company',
            field=models.CharField(max_length=30, verbose_name='회사명/회사코드'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(max_length=30, verbose_name='이름'),
        ),
        migrations.DeleteModel(
            name='EmailVerification',
        ),
    ]
